services: 
  api-gateway: 
    build: 
      context: api-gateway
    container_name: api-gateway-cont 
    environment: 
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
  user-service: 
    build: 
      context: user-service 
    container_name:  user-service-cont 
    environment: 
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8081:8080"
  product-service: 
    build: 
      context: product-service 
    #container_name:  product-service-cont 
    environment: 
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=docker
    # deploy:
    #   replicas: 2 
    # ports:
    #   - "8082:8080"
  eureka-service: 
    build: 
      context: eureka-server
    container_name:  eureka-service
    environment: 
      - SERVER_PORT=8761
     # - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8761:8761"