services: 
  api-gateway: 
    build: 
      context: api-gateway
    container_name:  api-gateway-cont 
    environment: 
      - SERVER_PORT = 8080
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
  user-service: 
    build: 
      context: user-service 
    container_name:  user-service-cont 
    environment: 
      - SERVER_PORT=8080
    ports:
      - "8081:8080"
  product-service: 
    build: 
      context: product-service 
    container_name:  product-service-cont 
    environment: 
      - SERVER_PORT=8080
    ports:
      - "8082:8080"
 