spring:
  config:
    import: "optional:configserver:http://localhost:8888"
  application:
    name: api-gateway
  cloud:
    config:
      uri: http://localhost:8888
      name: api-gateway
      profile: docker
      fail-fast: true