spring:
    config:
      import: "optional:configserver:http://config-server:8888"
    application:
      name: api_gateway
    cloud:
      config:
        uri: http://config-server:8888
        name: api_gateway
        profile: resilience
        fail-fast: true 