spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service
              # uri: http://localhost:8383
              uri: lb://product-service   # load balance URI
              predicates:
                - Path=/api/v1/products/**
              filters:
                - StripPrefix=0
            - id: user-service
              uri: http://localhost:8181
              predicates:
                #- Path=/api/v1/users/**
                # because I want to override the path
                - Path=/users/**
              filters:
                #- StripPrefix=0
                - RewritePath=/users/(?<segment>.*), /api/v1/users/$\{segment}
  application:
    name: api-gateway
# behold the configuration to know which is the eureka server
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#      fetch-registry: true
#      register-with-eureka: true
#  instance:
#    prefer-ip-address: true
#    hostname: localhost