#spring:
#  application:
#      name: api-gateway
#  profiles:
#    active: docker
spring:
  profiles:
    active: prod
  config:
    import: "optional:configserver:http://config-server:8888"
  application:
    name: api-gateway
  cloud:
    config:
      uri: http://localhost:8888
      name: api_gateway
      profile: resilience
      fail-fast: true
