spring:
    config:
      import: "optional:configserver:http://config-server:8888"
    application:
      name: api-gateway
    cloud:
      config:
        uri: http://config-server:8888
        name: api-gateway
        profile: dev
        fail-fast: true 