services: 
  zookeeper: 
    image: zookeeper 
    ports: 
      - "2181:2181"
  kafka: 
    image: bitnami/kafka 
    environment: 
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181 
      ALLOW_PLAINTEXT_LISTENER: "yes" 
    ports: 
      - "9092:9092"