server:
  port: 8081
spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
  config:
    import: "optional:configserver:http://localhost:8888"
  application:
    name: user-service
  cloud:
    config:
      uri: http://localhost:8888
      name: api-gateway
      profile: dev
      fail-fast: true