spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
  config:
    import: "optional:configserver:http://config-server:8888"
  application:
    name: user-service
  cloud:
    config:
      uri: http://config-server:8888
      name: user-service
      profile: default
      fail-fast: true

server:
  port: 8181
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka