server:
  port: 8081
spring:
  config:
    import: "optional:configserver:http://localhost:8888"
  application:
    name: user-service
  cloud:
    config:
      uri: http://localhost:8888
      name: api-gateway
      profile: dev
      fail-fast: true