#spring:
#    application:
#      name: product-service
#server:
#  port: 8383
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka


spring:

  config:
    import: "optional:configserver:http://config-server:8888"
  application:
    name: product-service # important must match config repo folder and vault-context
  cloud:
    config:
      uri: http://config-server:8888
      name: product-service
      profile: default
      fail-fast: true
    vault:
        uri: http://vault:8200
        authentication: token
        token: myroot
        kv:
            enabled: true
            backend: secret
            default-context: product-service
            profile-separator: '/'
            application-name: product-service
  # configuration for accessing the kafka cluster.
