# Production Profile
eureka:
  instance:
    hostname: eureka-server
    non-secure-port: 8761
    secure-port-enabled: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  server:
    # Enable self-preservation in production
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 30000
    renewal-percent-threshold: 0.85