spring:
  config:
    import: "optional:configserver:http://config-server:8888"
  application:
    name: eureka-server
  cloud:
    config:
      uri: http://config-server:8888
      name: eureka-server
      profile: default
      fail-fast: true