

spring:
  config:
    import: "optional:configserver:http://localhost:8888"
  application:
    name: eureka-server
  cloud:
    config:
      uri: http://localhost:8888
      name: eureka-server
      profile: dev
      fail-fast: true
server:
  port: 8888