server:
  port: 8888
spring:
 profiles:
   active: git, vault
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${GIT_CONFIG_REPO}
          default-label: ${GIT_CONFIG_BRANCH}
          search-paths:
            - config
            - '{application}'
          clone-on-start: true # clone the repo when server start 
        vault:
          host: vault
          port: 8200
          authentication: TOKEN
          token: ${VAULT_TOKEN}
          backend: secret
          kv-version: 2
          profile-separator: '/'